In [34]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array([0, np.pi/4, np.pi/2])
a = torch.Tensor(a)
print(a)

tensor([0.0000, 0.7854, 1.5708])


C:\Users\joanb\AppData\Local\Temp\ipykernel_2552\658851343.py:2: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  a = torch.Tensor(a)


In [3]:
torch.sin(a)

tensor([0.0000, 0.7071, 1.0000])

In [17]:
torch.nn.functional.gumbel_softmax(tau=1, hard=False, logits=torch.Tensor([0.5,0.5]))

tensor([0.8638, 0.1362])

In [19]:
logits = torch.randn(2, 2)
logits

tensor([[-0.8803, -1.1755],
        [ 0.3911, -0.5090]])

In [31]:
torch.nn.functional.gumbel_softmax(logits, tau=0.1, hard=True)

tensor([[1., 0.],
        [0., 1.]])

In [55]:
N = 10**1
tau = 0.001
probs = np.array([0.3, 0.2, 0.5])
logits = torch.Tensor(np.log(probs))
s = 0

for i in range(N):
    s += torch.nn.functional.gumbel_softmax(logits, tau=tau, hard=True)

print(s/N)

tensor([0.3000, 0.3000, 0.4000])
