In [2]:
import pandas as pd
import numpy as np
import torch
from torch_smodel import *

In [2]:
Theta = np.random.uniform(low=0, high=2*np.pi, size=10)
Q_ = np.array(Theta/(np.pi/2) + 1, dtype='int8')
Q_, Theta

(array([2, 4, 2, 1, 3, 3, 2, 2, 2, 3], dtype=int8),
 array([2.24729955, 5.12862958, 2.45682906, 0.66539925, 4.65442817,
        4.30632077, 1.98156554, 1.95470749, 2.42604023, 3.38274587]))

In [3]:
a = np.array([Q(b) for b in Theta])

In [4]:
a

array([2, 4, 2, 1, 3, 3, 2, 2, 2, 3])

In [5]:
T_theta = [T(b) for b in Theta]
T_theta

[0.8942931076307636,
 1.1545557279496679,
 0.6847635950931208,
 0.6653992502420045,
 1.5128355186342448,
 1.1647281208341003,
 1.160027115070257,
 1.1868851678213792,
 0.7155524198920187,
 0.24115321182122118]

In [12]:
torch.where(
    torch.logical_or(torch.from_numpy(Q_) == 1, torch.from_numpy(Q_) == 3),
    #Q in [1,3],
    torch.from_numpy(Theta - ((Q_-1)/2)*torch.pi),
    torch.from_numpy((Q_/2)*torch.pi - Theta)
)

tensor([0.8943, 1.1546, 0.6848, 0.6654, 1.5128, 1.1647, 1.1600, 1.1869, 0.7156,
        0.2412], dtype=torch.float64)

In [13]:
T_theta

[0.8942931076307636,
 1.1545557279496679,
 0.6847635950931208,
 0.6653992502420045,
 1.5128355186342448,
 1.1647281208341003,
 1.160027115070257,
 1.1868851678213792,
 0.7155524198920187,
 0.24115321182122118]

In [3]:
columnas = ['Theta', 'Quadrant', 'Xi', 'Rho', 'm', 'Susceptibles', 'Infecteds', 'Deads']
df = pd.DataFrame(index = range(10 + 1), columns = columnas)
df.iloc[0] = [None, None, None, None, None, 1, 1, 1]

In [16]:
df.Theta[1:]=torch.tensor(range(10))

In [15]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
df.Theta[0:3] = torch.tensor([1,2,3])

In [19]:
df

Theta Quadrant    Xi   Rho     m Susceptibles Infecteds Deads
0      1     None  None  None  None            1         1     1
1      2      NaN   NaN   NaN   NaN          NaN       NaN   NaN
2      3      NaN   NaN   NaN   NaN          NaN       NaN   NaN
3      2      NaN   NaN   NaN   NaN          NaN       NaN   NaN
4      3      NaN   NaN   NaN   NaN          NaN       NaN   NaN
5      4      NaN   NaN   NaN   NaN          NaN       NaN   NaN
6      5      NaN   NaN   NaN   NaN          NaN       NaN   NaN
7      6      NaN   NaN   NaN   NaN          NaN       NaN   NaN
8      7      NaN   NaN   NaN   NaN          NaN       NaN   NaN
9      8      NaN   NaN   NaN   NaN          NaN       NaN   NaN
10     9      NaN   NaN   NaN   NaN          NaN       NaN   NaN