In [1]:
from torch_smodel import *

KeyboardInterrupt: 

In [ ]:
grid = Grid(N=11)

In [ ]:
grid.neigh_prob

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
E, P = init(11, 5)

In [ ]:
grid.submatrix(np.pi/4)
grid.A

tensor([[0.0000, 0.7071, 1.0000],
        [0.0000, 0.0000, 0.7071],
        [0.0000, 0.0000, 0.0000]], dtype=torch.float64)

In [ ]:
torch.sin(torch.Tensor([np.pi/4])).shape

torch.Size([1])

In [ ]:
A = torch.zeros(3,3)
A[1,1] = 1
A[1,2] = 1.5
A[2,2] = 3

In [ ]:
A

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 1.5000],
        [0.0000, 0.0000, 3.0000]])

In [ ]:
A[np.logical_and(A>=1, A<3)]=20

C:\Users\joanb\AppData\Local\Temp\ipykernel_17180\3829182568.py:1: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1582.)
  A[np.logical_and(A>=1, A<3)]=20


In [ ]:
A

tensor([[ 0.,  0.,  0.],
        [ 0., 20., 20.],
        [ 0.,  0.,  3.]])

In [ ]:
A = torch.randn(3,3)
A

tensor([[ 1.7125, -0.8775, -0.8753],
        [-0.8195,  0.4685,  0.3612],
        [ 1.7169,  0.1308, -0.4445]])

In [ ]:
aux = np.logical_and(A>0, A<1)
aux

tensor([[0, 0, 0],
        [0, 1, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [ ]:
for p in A[(aux==1)]:
    print(torch.Tensor([p, 1-p]))

tensor([0.4685, 0.5315])
tensor([0.3612, 0.6388])
tensor([0.1308, 0.8692])


In [ ]:
list(zip(np.where(np.logical_and(A>0, A<1))[0],np.where(np.logical_and(A>0, A<1))[1]))

[(1, 1), (1, 2), (2, 1)]

In [ ]:
B = torch.Tensor(np.random.randint(0, 2, 9).reshape(3,3))
B

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
aux = np.logical_and(A < 1, A > 0)
ind_test = np.logical_and(B==0, aux)

In [ ]:
np.where(ind_test==1)

(array([1, 2], dtype=int64), array([2, 1], dtype=int64))

In [ ]:
a = torch.Tensor([1,1,1])
a.log()

tensor([0., 0., 0.])

In [ ]:
torch.random.manual_seed(0)
np.random.seed(0)
A = torch.randn(3,3)
B = torch.Tensor(np.random.randint(0, 2, 9).reshape(3,3))
A, B

(tensor([[ 1.5410, -0.2934, -2.1788],
         [ 0.5684, -1.0845, -1.3986],
         [ 0.4033,  0.8380, -0.7193]]),
 tensor([[0., 1., 1.],
         [0., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
torch.sum(torch.randn(2,2))

tensor(-1.6746)

In [ ]:
from torch_smodel import *

In [ ]:
rho = 0.95
theta = np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)

In [ ]:
grid.submatrix(theta=theta)
grid.A

tensor([[0.0000, 0.5000, 0.5774],
        [0.0000, 0.0000, 0.8660],
        [0.0000, 0.0000, 0.0000]], dtype=torch.float64)

In [ ]:
T(theta=theta), Q(theta=theta)

(0.5235987755982988, 1)

In [ ]:
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.1250, 0.1347, 0.1395, 0.1443],
        [0.0000, 0.0000, 0.0000, 0.2500, 0.2693, 0.2887, 0.1624],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5774, 0.3608, 0.1804],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8660, 0.4330, 0.2165],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [ ]:
rho = 0.95
theta = 5*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.1443, 0.1395, 0.1347, 0.1250, 0.0000, 0.0000, 0.0000],
        [0.1624, 0.2887, 0.2693, 0.2500, 0.0000, 0.0000, 0.0000],
        [0.1804, 0.3608, 0.5774, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.2165, 0.4330, 0.8660, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [ ]:
rho = 0.95
theta = 11*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8660, 0.4330, 0.2165],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5774, 0.3608, 0.1804],
        [0.0000, 0.0000, 0.0000, 0.2500, 0.2693, 0.2887, 0.1624],
        [0.0000, 0.0000, 0.0000, 0.1250, 0.1347, 0.1395, 0.1443]],
       dtype=torch.float64)

In [ ]:
rho = 0.95
theta = 7*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2165, 0.4330, 0.8660, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1804, 0.3608, 0.5774, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.1624, 0.2887, 0.2693, 0.2500, 0.0000, 0.0000, 0.0000],
        [0.1443, 0.1395, 0.1347, 0.1250, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [ ]:
E, P, df = SpreadModel(N=11, K=5, seed_value=0, inc=2)

In [ ]:
df

Theta Quadrant       Rho     m  Susceptibles  Infecteds  Deads
0      None     None      None  None           120          1      0
1  3.448297        3  0.645894     2           118          3      0
2  4.493667        3  0.437587     1           114          6      1
3  3.787274        3  0.891773     2           105         13      3
4  3.423602        3  0.963663     3            93         21      7
5  2.661902        2  0.383442     1            89         16     16

In [ ]:
E[:,:,2], P[:,:,1]

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int8),
 tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.

# Probamos la expansion dentro de la class

In [ ]:
from torch_smodel import * 

In [11]:
grid = Grid(N=11)

In [12]:
grid.__param__()
grid.Expansion()
grid.df

Theta Quadrant       Rho     m  Susceptibles  Infecteds  Deads
0       None     None      None  None           120          1      0
1   0.058802        1  0.831353     2           119          1      1
2   3.135673        2  0.827568     2           119          0      2
3   0.712411        1   0.83358     2           119          0      2
4   0.313996        1  0.957044     3           119          0      2
5   4.306543        3  0.368044     1           119          0      2
6   3.059836        2  0.494838     1           119          0      2
7   5.640147        4  0.339509     1           119          0      2
8   4.068061        3  0.619429     2           119          0      2
9   5.635786        4   0.97753     3           119          0      2
10  4.531024        3  0.096433     1           119          0      2

In [4]:
df2 = grid.df[['Theta', 'Rho']].drop(0).copy()

In [5]:
E, P, df3 = SpreadModel(N=11, K=10, seed_value=0, input=True, data=df2)
df3

Theta Quadrant       Rho     m  Susceptibles  Infecteds  Deads
0       None     None      None  None           120          1      0
1   3.448297        3  0.791725     2           118          2      1
2   4.493667        3  0.528895     2           114          4      3
3   3.787274        3  0.568045     2           106          8      7
4   3.423602        3  0.925597     3            98          8     15
5   2.661902        2  0.071036     1            97          1     23
6   4.058272        3  0.087129     1            94          3     24
7   2.749442        2  0.020218     1            91          3     27
8   5.603175        4   0.83262     2            89          2     30
9   6.054872        4  0.778157     2            88          1     32
10  2.409234        2  0.870012     2            84          4     33

In [6]:
grid2 = Grid(N=11)
grid2.__param__()
grid2.MonteCarlo(input=True, data=df2)

In [7]:
grid2.df_MC

Empty DataFrame
Columns: [Theta, Quadrant, Rho, m, Susceptibles, Infecteds, Deads]
Index: []

In [8]:
A = torch.randint(0,2, size=(3,3))
B = torch.randint(0,2, size=(3,3))

In [9]:
A, B

(tensor([[0, 0, 1],
         [1, 0, 1],
         [1, 1, 1]]),
 tensor([[1, 0, 1],
         [1, 0, 0],
         [0, 1, 0]]))

In [10]:
((A==1)*1 + (B==1)*1)/2

tensor([[0.5000, 0.0000, 1.0000],
        [1.0000, 0.0000, 0.5000],
        [0.5000, 1.0000, 0.5000]])

In [14]:
grid2.X0[:,:,0].numpy()

array([[1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 0.001, 0.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [0.001, 0.001, 0.001, 0.001, 0.001, 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [0.001, 0.001, 0.001, 0.001, 0.001, 1.   , 1.   , 1.   , 1.   ,
        1.   , 1.   ],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.001,
        1.   , 1.   ],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 1.   ,
        1.   , 1.   ],
       [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0

In [ ]:
grid = Grid(N=21)

In [ ]:
grid.__param__()
grid.Expansion()
grid.S[:, :, 0]

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [22]:
E, P, df = SpreadModel()

In [27]:
E[:,:,4]

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]], dtype=torch.int8)