In [1]:
from torch_smodel import *

In [2]:
grid = Grid(N=11)

In [3]:
grid.neigh_prob

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [4]:
E, P = init(11, 5)

In [5]:
grid.submatrix(np.pi/4)
grid.A

tensor([[0.0000, 0.7071, 1.0000],
        [0.0000, 0.0000, 0.7071],
        [0.0000, 0.0000, 0.0000]], dtype=torch.float64)

In [6]:
torch.sin(torch.Tensor([np.pi/4])).shape

torch.Size([1])

In [7]:
A = torch.zeros(3,3)
A[1,1] = 1
A[1,2] = 1.5
A[2,2] = 3

In [8]:
A

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 1.5000],
        [0.0000, 0.0000, 3.0000]])

In [9]:
A[np.logical_and(A>=1, A<3)]=20

C:\Users\joanb\AppData\Local\Temp\ipykernel_12624\3829182568.py:1: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1582.)
  A[np.logical_and(A>=1, A<3)]=20


In [10]:
A

tensor([[ 0.,  0.,  0.],
        [ 0., 20., 20.],
        [ 0.,  0.,  3.]])

In [11]:
A = torch.randn(3,3)
A

tensor([[ 0.9480, -0.3201, -0.1643],
        [-0.3154,  0.1081, -0.1735],
        [ 0.1981, -0.2844, -0.5775]])

In [12]:
aux = np.logical_and(A>0, A<1)
aux

tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 0]], dtype=torch.uint8)

In [13]:
for p in A[(aux==1)]:
    print(torch.Tensor([p, 1-p]))

tensor([0.9480, 0.0520])
tensor([0.1081, 0.8919])
tensor([0.1981, 0.8019])


In [14]:
list(zip(np.where(np.logical_and(A>0, A<1))[0],np.where(np.logical_and(A>0, A<1))[1]))

[(0, 0), (1, 1), (2, 0)]

In [15]:
B = torch.Tensor(np.random.randint(0, 2, 9).reshape(3,3))
B

tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 1., 1.]])

In [16]:
aux = np.logical_and(A < 1, A > 0)
ind_test = np.logical_and(B==0, aux)

In [17]:
np.where(ind_test==1)

(array([1], dtype=int64), array([1], dtype=int64))

In [18]:
a = torch.Tensor([1,1,1])
a.log()

tensor([0., 0., 0.])

In [19]:
torch.random.manual_seed(0)
np.random.seed(0)
A = torch.randn(3,3)
B = torch.Tensor(np.random.randint(0, 2, 9).reshape(3,3))
A, B

(tensor([[ 1.5410, -0.2934, -2.1788],
         [ 0.5684, -1.0845, -1.3986],
         [ 0.4033,  0.8380, -0.7193]]),
 tensor([[0., 1., 1.],
         [0., 1., 1.],
         [1., 1., 1.]]))

In [21]:
torch.sum(torch.randn(2,2))

tensor(-0.0842)

In [1]:
from torch_smodel import *

In [2]:
rho = 0.95
theta = np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)

In [3]:
grid.submatrix(theta=theta)
grid.A

tensor([[0.0000, 0.5000, 0.5774],
        [0.0000, 0.0000, 0.8660],
        [0.0000, 0.0000, 0.0000]], dtype=torch.float64)

In [4]:
T(theta=theta), Q(theta=theta)

(0.5235987755982988, 1)

In [5]:
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.1250, 0.1347, 0.1395, 0.1443],
        [0.0000, 0.0000, 0.0000, 0.2500, 0.2693, 0.2887, 0.1624],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5774, 0.3608, 0.1804],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8660, 0.4330, 0.2165],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [6]:
rho = 0.95
theta = 5*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.1443, 0.1395, 0.1347, 0.1250, 0.0000, 0.0000, 0.0000],
        [0.1624, 0.2887, 0.2693, 0.2500, 0.0000, 0.0000, 0.0000],
        [0.1804, 0.3608, 0.5774, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.2165, 0.4330, 0.8660, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [7]:
rho = 0.95
theta = 11*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8660, 0.4330, 0.2165],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5774, 0.3608, 0.1804],
        [0.0000, 0.0000, 0.0000, 0.2500, 0.2693, 0.2887, 0.1624],
        [0.0000, 0.0000, 0.0000, 0.1250, 0.1347, 0.1395, 0.1443]],
       dtype=torch.float64)

In [8]:
rho = 0.95
theta = 7*np.pi/6
partition = [0.1, 0.5, 0.9]
inc = 1
p0 = 0.25
div = 2

grid = Grid(N=7)
grid.submatrix(theta=theta)
grid.enlargement_process(theta=theta, rho=rho, partition=partition, p0=p0, div=div)
grid.large_matrix

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2165, 0.4330, 0.8660, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1804, 0.3608, 0.5774, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.1624, 0.2887, 0.2693, 0.2500, 0.0000, 0.0000, 0.0000],
        [0.1443, 0.1395, 0.1347, 0.1250, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [9]:
E, P, df = SpreadModel(N=11, K=5, seed_value=0, inc=2)

c:\Users\joanb\Desktop\PyTorch\torch_smodel.py:183: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1582.)
  self.state[np.logical_and(self.neigh_prob >= 1, self.state==0)] = 1
c:\Users\joanb\Desktop\PyTorch\torch_smodel.py:184: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1582.)
  self.state[np.logical_and(self.neigh_prob <= 0, self.state==0)] = 0
c:\Users\joanb\Desktop\PyTorch\torch_smodel.py:183: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1582.)
  self.stat

In [10]:
df

Theta Quadrant       Rho     m  Susceptibles  Infecteds  Deads
0      None     None      None  None           120          1      0
1  3.448297        3  0.645894     2           118          3      0
2  4.493667        3  0.437587     1           114          6      1
3  3.787274        3  0.891773     2           105         13      3
4  3.423602        3  0.963663     3            93         21      7
5  2.661902        2  0.383442     1            89         16     16

In [11]:
E[:,:,2], P[:,:,1]

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int8),
 tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.