In [10]:
import pandas as pd
import numpy as np
import torch
from torch_smodel import *
import torch.nn.functional as F

In [28]:
import torch

# Supongamos que tienes una matriz cuadrada de 3x3
matrix = [[0.2, 0.5, 0.7], [0.1, 0.6, 0.8], [0.3, 0.4, 0.9]]

# Creamos un tensor de PyTorch a partir de la matriz
tensor = torch.tensor(matrix)

# Calculamos el complementario de cada elemento del tensor
complementary = 1 - tensor

# Concatenamos el tensor y su complementario en una única matriz
vectors = torch.stack([tensor, complementary], dim=-1)

# Aplanamos la matriz de vectores en un array de una única columna
array = vectors.flatten().view((3,3,2))

# Imprimimos el array por pantalla
print(array)

tensor([[[0.2000, 0.8000],
         [0.5000, 0.5000],
         [0.7000, 0.3000]],

        [[0.1000, 0.9000],
         [0.6000, 0.4000],
         [0.8000, 0.2000]],

        [[0.3000, 0.7000],
         [0.4000, 0.6000],
         [0.9000, 0.1000]]])


In [26]:
#F.gumbel_softmax(array.view(3,3,2), tau=0.5, hard=True)

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.],
         [1., 0.]]])

In [29]:
logits = array.log()
logits

tensor([[[-1.6094, -0.2231],
         [-0.6931, -0.6931],
         [-0.3567, -1.2040]],

        [[-2.3026, -0.1054],
         [-0.5108, -0.9163],
         [-0.2231, -1.6094]],

        [[-1.2040, -0.3567],
         [-0.9163, -0.5108],
         [-0.1054, -2.3026]]])

In [71]:
import torch

# Crea un tensor de shape (3, 3, 5) con valores aleatorios
A = torch.rand((3, 3, 5))
A_t = torch.transpose(A, 0, 1)
# Crea un tensor de shape (3, 3, 5) lleno de ceros
#B = torch.zeros_like(A)

# Itera a través de las primeras dos dimensiones de A

A[:,:,3], A_t[:,:,3]
 

(tensor([[0.8035, 0.2317, 0.6279],
         [0.8268, 0.8375, 0.0307],
         [0.2889, 0.3375, 0.5076]]),
 tensor([[0.8035, 0.8268, 0.2889],
         [0.2317, 0.8375, 0.3375],
         [0.6279, 0.0307, 0.5076]]))

In [30]:
v = F.gumbel_softmax(logits=logits, tau=0.5, hard=True)
for i in range(9999):
    v += F.gumbel_softmax(logits=logits, tau=0.1, hard=True)
v = v/9999

In [31]:
v

tensor([[[0.1989, 0.8012],
         [0.4961, 0.5040],
         [0.6962, 0.3039]],

        [[0.0988, 0.9013],
         [0.5976, 0.4025],
         [0.8165, 0.1836]],

        [[0.3026, 0.6975],
         [0.3938, 0.6063],
         [0.8986, 0.1015]]])

In [86]:
a = v[:, 1].unsqueeze(1)
a

tensor([[0.7950],
        [0.5037],
        [0.3044],
        [0.8988],
        [0.3980],
        [0.1990],
        [0.7021],
        [0.5999],
        [0.0975]])

In [3]:
Theta = torch.from_numpy(np.random.uniform(low=0, high=2*np.pi, size=10))
Q_ = (Theta/(np.pi/2) + 1).type(torch.int8)
Q_, Theta

(tensor([1, 1, 3, 3, 1, 4, 2, 3, 2, 3], dtype=torch.int8),
 tensor([0.5688, 0.4614, 3.9108, 3.2038, 0.7585, 5.8441, 2.5679, 3.5997, 1.8629,
         4.5957], dtype=torch.float64))

In [5]:
p = torch.zeros(7,7, dtype=torch.float64)
p[2:5,2:5] = 0.25
p[3,3] = 0
p[2:5, 2:]

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2500, 0.0000, 0.2500, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [17]:
s = torch.randint(size=(5, 5), low=0, high=2)
S = torch.randint(size=(5, 5, 3), low=0, high=2)
s, S

(tensor([[0, 1, 1, 1, 1],
         [0, 0, 0, 0, 1],
         [0, 1, 1, 1, 0],
         [0, 1, 1, 0, 0],
         [1, 0, 0, 1, 0]]),
 tensor([[[1, 1, 0],
          [0, 0, 0],
          [1, 0, 1],
          [1, 1, 1],
          [0, 1, 0]],
 
         [[0, 1, 1],
          [1, 0, 0],
          [1, 1, 1],
          [0, 1, 1],
          [0, 1, 1]],
 
         [[0, 0, 1],
          [1, 0, 0],
          [1, 0, 0],
          [1, 0, 1],
          [0, 0, 1]],
 
         [[0, 0, 0],
          [0, 1, 1],
          [0, 1, 0],
          [1, 1, 1],
          [1, 0, 1]],
 
         [[0, 1, 1],
          [0, 0, 0],
          [1, 0, 1],
          [1, 0, 0],
          [0, 1, 1]]]))

In [18]:
s == 1

tensor([[False,  True,  True,  True,  True],
        [False, False, False, False,  True],
        [False,  True,  True,  True, False],
        [False,  True,  True, False, False],
        [ True, False, False,  True, False]])

In [30]:
import torch.nn.functional as F

s = torch.randint(size=(7, 7), low=0, high=2)
prob = torch.zeros((7,7), dtype=torch.float64)
prob[1:-1, 1:-1] = torch.rand(size=(5,5))

In [33]:
torch.where(
    torch.logical_and(s==0, torch.logical_and(prob < 1, prob > 0)),
    F.gumbel_softmax(torch.Tensor([prob, 1-prob]).log(), hard=True)[1],
    s
)

ValueError: only one element tensors can be converted to Python scalars

In [38]:
F.gumbel_softmax(torch.rand(size=(3,3)), tau=0.5, hard=True)

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]])

In [3]:
a = np.array([Q(b) for b in Theta])

In [4]:
a

array([2, 4, 2, 1, 3, 3, 2, 2, 2, 3])

In [5]:
T_theta = [T(b) for b in Theta]
T_theta

[0.8942931076307636,
 1.1545557279496679,
 0.6847635950931208,
 0.6653992502420045,
 1.5128355186342448,
 1.1647281208341003,
 1.160027115070257,
 1.1868851678213792,
 0.7155524198920187,
 0.24115321182122118]

In [12]:
torch.where(
    torch.logical_or(torch.from_numpy(Q_) == 1, torch.from_numpy(Q_) == 3),
    #Q in [1,3],
    torch.from_numpy(Theta - ((Q_-1)/2)*torch.pi),
    torch.from_numpy((Q_/2)*torch.pi - Theta)
)

tensor([0.8943, 1.1546, 0.6848, 0.6654, 1.5128, 1.1647, 1.1600, 1.1869, 0.7156,
        0.2412], dtype=torch.float64)

In [13]:
T_theta

[0.8942931076307636,
 1.1545557279496679,
 0.6847635950931208,
 0.6653992502420045,
 1.5128355186342448,
 1.1647281208341003,
 1.160027115070257,
 1.1868851678213792,
 0.7155524198920187,
 0.24115321182122118]

In [3]:
columnas = ['Theta', 'Quadrant', 'Xi', 'Rho', 'm', 'Susceptibles', 'Infecteds', 'Deads']
df = pd.DataFrame(index = range(10 + 1), columns = columnas)
df.iloc[0] = [None, None, None, None, None, 1, 1, 1]

In [16]:
df.Theta[1:]=torch.tensor(range(10))

In [15]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
df.Theta[0:3] = torch.tensor([1,2,3])

In [19]:
df

Theta Quadrant    Xi   Rho     m Susceptibles Infecteds Deads
0      1     None  None  None  None            1         1     1
1      2      NaN   NaN   NaN   NaN          NaN       NaN   NaN
2      3      NaN   NaN   NaN   NaN          NaN       NaN   NaN
3      2      NaN   NaN   NaN   NaN          NaN       NaN   NaN
4      3      NaN   NaN   NaN   NaN          NaN       NaN   NaN
5      4      NaN   NaN   NaN   NaN          NaN       NaN   NaN
6      5      NaN   NaN   NaN   NaN          NaN       NaN   NaN
7      6      NaN   NaN   NaN   NaN          NaN       NaN   NaN
8      7      NaN   NaN   NaN   NaN          NaN       NaN   NaN
9      8      NaN   NaN   NaN   NaN          NaN       NaN   NaN
10     9      NaN   NaN   NaN   NaN          NaN       NaN   NaN